#!/bin/sh

if ! head -1 "$1" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|chore|build|ci|revert|wip|improvement|update)(\(.+?\))?: .{1,}$"; then
  echo "ERROR: Commit message does not follow the conventional commit format." >&2
  echo "Please use one of the following types: feat, fix, docs, style, refactor, perf, test, chore, build, ci, revert, wip, improvement, update." >&2
  exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
  echo "ERROR: Aborting commit. Commit message is too long." >&2
  exit 1
fi